version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: hotel-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: hotel-backend
    ports:
      - "5000:5000"
    volumes:
      - hotel-data:/app/data
    environment:
      - PORT=5000
      - JWT_SECRET=secure_secret_key_123
      - MONGODB_URI=mongodb://hotel-mongodb:27017/hotelDB
      - ADMIN_EMAIL=admin@tnstay.com
      - ADMIN_PASSWORD=admin@123
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3000/api
    container_name: hotel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  hotel-data:
  mongodb-data:
